<?php
declare(strict_types=1);

/**
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
?>
<!-- ko scope: 'customer' -->
    <!-- ko if: customer().hobby -->
    <li class="customer-hobby">
        <span class="hobby-text"
              data-bind="text: '<?= $escaper->escapeJs(__('Hobby: %1')) ?>'.replace('%1', customer().hobby)">
        </span>
    </li>
    <!-- /ko -->
<!-- /ko -->
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}
</script>
